app:
  frontend:
    url: http://localhost:4200
  mapping:
    style: style-base.json

resilience:
  thread-pool:
    core-size: 8
    max-size: 10
    queue-capacity: 20


spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

  datasource:
    driverClassName: org.postgresql.Driver
    password: demo123
    url: jdbc:postgresql://localhost:5434/location_allocation
    username: postgres

  devtools:
    add-properties: false

  docker:
    compose:
      enabled: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    show-sql: false

#levelDB configuration
leveldb:
  root: C:\\Data\\ATP\\neo4j\\dmatrix\\

logging:
  level:
    root: WARN
    org:
      springframework: INFO
      hibernate:
        type: TRACE

