app:
    frontend:
        url: http://10.1.2.81:8080
    mapping:
        style: style-base.json
server:
    port: 8080

spring:
    batch:
        jdbc:
            initialize-schema: never # changed from 'always' in production
        job:
            enabled: true
    datasource:
        driverClassName: org.postgresql.Driver
        password: demo123
        url: jdbc:postgresql://pccuda.wigeo.lan:5432/location_allocation
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none  # changed from 'update' in production
        open-in-view: false  # change to 'false' to disable Open Session in View in production
        properties:
            hibernate:
                format_sql: true
        show-sql: false

resilience:
    thread-pool:
        core-size: 8
        max-size: 10
        queue-capacity: 20

logging:
    level:
        root: WARN
        org:
            springframework: INFO
            hibernate:
                type: TRACE