# Connection keep alive timeout [default: 75]
keep_alive: 100

# The socket address to bind [default: 0.0.0.0:3000]
listen_addresses: '0.0.0.0:3000'

# Number of web server workers
worker_processes: 8

postgres:
  connection_string: postgresql://postgres:demo123@postgis:5432/location_allocation

  #  If a spatial table has SRID 0, then this SRID will be used as a fallback
  default_srid: 3857

  # Maximum connections pool size [default: 20]
  pool_size: 500

  # Control the automatic generation of bounds for spatial tables [default: false]
  # If enabled, it will spend some time on startup to compute geometry bounds.
  disable_bounds: false

  # Enable automatic discovery of tables and functions.
  # You may set this to `false` to disable.
  auto_publish: false

  # Associative arrays of table sources
  tables:
    landuse:
      schema: public

      table: region

      srid: 3857

      geometry_column: geom

      properties:
        country_code: varchar
        id: int4
        name: varchar
        region_code: varchar

      # Feature id column name
      id_column: id

      # An integer specifying the minimum zoom level
      minzoom: 0

      # An integer specifying the maximum zoom level. MUST be >= minzoom
      maxzoom: 30

      # The maximum extent of available map tiles. Bounds MUST define an area
      # covered by all zoom levels. The bounds are represented in WGS:84
      # latitude and longitude values, in the order left, bottom, right, top.
      # Values may be integers or floating point numbers.
      bounds: [-180.0, -90.0, 180.0, 90.0]

      # Tile extent in tile coordinate space
      extent: 4096

      # Buffer distance in tile coordinate space to optionally clip geometries
      buffer: 64

      # Boolean to control if geometries should be clipped or encoded as is
      clip_geom: true

      # Geometry type
      geometry_type: GEOMETRY


  # Associative arrays of function sources
  functions:
    fn_allocation_zxy_query:
      # Schema name (required)
      schema: public

      # Function name (required)
      function: fn_allocation_zxy_query

      # An integer specifying the minimum zoom level
      minzoom: 0

      # An integer specifying the maximum zoom level. MUST be >= minzoom
      maxzoom: 30

      bounds: [-180.0, -90.0, 180.0, 90.0]

    fn_region_zxy_query:
      schema: public

      function: fn_region_zxy_query
      # An integer specifying the minimum zoom level
      minzoom: 0

      # An integer specifying the maximum zoom level. MUST be >= minzoom
      maxzoom: 30

      bounds: [ -180.0, -90.0, 180.0, 90.0 ]